# Generated by Django 3.0.4 on 2020-04-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=560)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('release_date',),
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=560)),
                ('music_releases', models.ManyToManyField(blank=True, to='core.MusicRelease')),
            ],
        ),
    ]
